config/routes.rb
Rails.application.routes.draw do
  get 'blip/new'
  get 'blip/create'
  get 'blip/show'
  devise_for :users
  resources :links
  root to: "links#index"
  get '/:link_id', to: 'links#id_search'
  get '/:link_id/edit', to: 'links#edit', as: 'link_edit'
  get '/user/profile', to: 'links#profile'
  get '/pages/:page', to: 'links#index', as: 'paginate_links'
  get '/download/export_to_csv', to: 'links#export_to_csv', as: :export_to_csv
  resources :blip, only: [:new, :create, :index, :show]
  post '', to: 'links#verification'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true

  serialize :properties, coder: JSON
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/birthday.rb
class Birthday < ApplicationRecord
    validates :user_id, presence: true
    validates :birthday, presence: true
end

app/models/blip.rb
class Blip < ApplicationRecord
  before_create :generate_unique_url
  belongs_to :user

  private

  def generate_unique_url
    loop do
      self.unique_url = SecureRandom.hex(10)
      break unless self.class.exists?(unique_url: unique_url)
    end
  end
end

app/models/link.rb
class Link < ApplicationRecord
  extend FriendlyId
  friendly_id :link_id, use: :slugged

  paginates_per 12
  belongs_to :user, optional: true
  has_many :events, class_name: 'Ahoy::Event', as: :subject

  def click_count
    Ahoy::Event.where(name: "Link clicked")
              .where("properties::json -> 'link_id' ->> 'id' = ?", id.to_s)
              .count
  end

  def shortened_url
    ENV["ROOT_URL"] + self.link_id
  end

  def full_url
    url = self.url
    url = "https://#{url}" unless url.start_with?('http://', 'https://')
    url 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_initialize :init

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links
  has_many :blips
  has_many :events, class_name: 'Ahoy::Event', as: :subject
  has_many :visits, class_name: "Ahoy::Visit"

  def admin?
    self.role == "admin"
  end

  def user?
    self.role == "user"
  end

  def promote_to_admin
    self.update(role: "admin")
  end

  def demote_to_user
    self.update(role: "user")
  end

  def change_role(new_role)
    self.update(role: new_role)
  end

  def init
    self.role ||= "user"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blip_controller.rb
class BlipController < ApplicationController
  def index
    @blips = Blip.all
  end

  def new
    @blip = Blip.new
  end

  def create
    @blip = Blip.new(blip_params)
    if @blip.save
      redirect_to blip_path(@blip.unique_url)
    else
      render :new
    end
  end

  def show
    @blip = Blip.find_by!(unique_url: params[:id])
  end

  private

  def blip_params
    params.require(:blip).permit(:content)
  end
end

app/controllers/links_controller.rb
require 'securerandom'
require 'csv'

class LinksController < ApplicationController
  before_action :set_link, only: %i[ show destroy ]
  after_action :track_link_click, only: %i[ id_search show ]
  skip_before_action :verify_authenticity_token

  def index
    @link = Link.new
    @links = links_for_role
    @discord_creds_avail = Rails.application.credentials['discord_bot_token'].present?
    puts @discord_creds_avail
  end

  def edit
    @link = Link.friendly.find params[:link_id]
    render json: { url: @link.url, shortened: @link.shortened_url }
  end

  def new
    @link = Link.new
  end

  def profile
    @links = current_user.links
  end

  def create
    @link = current_user ? current_user.links.new(link_params) : Link.new(link_params)
    @link.link_id = new_unique_id

    respond_to do |format|
      if @link.save
        format.html { redirect_to root_path, notice: "Link was successfully saved." }
        ahoy.track "Link created", link_id: @link.id
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link = current_user.links.friendly.find(params[:id])
    @link.destroy!
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def id_search
    @link = Link.find_by(link_id: params[:link_id])
    if @link.present?
      redirect_to @link.full_url, allow_other_host: true
    else
      render json: { error: "404, link not found" }, status: :not_found
    end
  end

  def verification
    puts params
    render json: { message: "success" }
  end

  private

    def links_for_role
    if current_user.nil? || current_user.role == "admin"
      @links = Link.where.not(link_id: nil).order(created_at: :desc).page(params[:page]).per(12)
    elsif current_user.role == "user"
      @links = Link.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(12)
    else
      render json: { error: "503, no links available for this role" }
    end
  end

  def export_to_csv
    @links = links_for_role

    csv_data = CSV.generate(headers: true) do |csv|
      csv << [ "original_url", "shortened_url", "click_count" ]

      @links.each do |link|
        csv << [ link.url, full_url(link.slug), link.click_count]
      end
    end

    send_data csv_data, filename: "my_links.csv"
  end

  def full_url(slug)
    root_url.to_s + slug.to_s
  end

  def new_unique_id
    loop do
      id = SecureRandom.uuid.last(10)
      return id unless Link.exists?(link_id: id)
    end
  end

  def set_link
    @link = Link.friendly.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:url)
  end

  def track_link_click
    ahoy.track "Link clicked", link_id: @link
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blip_helper.rb
module BlipHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/blip/create.html.erb
<h1>Blip#create</h1>
<p>Find me in app/views/blip/create.html.erb</p>

app/views/blip/index.html.erb
<% @blips.each do |blip| %>
  blip_show(blip)
<% end %>

app/views/blip/new.html.erb
<%= form_with model: @blip, url: blip_index_path do |form| %>
  <%= form.text_area :content %>
  <%= form.submit "Create Blip" %>
<% end %>

app/views/blip/show.html.erb
<%= raw Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@blip.content) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>curl.lol</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('logo.png')%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<div class="new-link-form-container">
  <%= form_with(model: @link) do |form| %>
    <% if @link.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
          <% @link.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.text_field :url, placeholder: "Enter URL here", class: "new-link-form-input" %>
    </div>

    <div>
      <%= form.submit "Create Link", class: "new-link-form-submit" %>
    </div>
  <% end %>
</div>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">

</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Show this link", @link %> |
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>curl.lol</h1>
<p class="center"> Click "Create Link" to add a new URL. Then, copy the Short url to use your new link!</p>
<div class="info">
  <% if current_user.nil? %>
    <%= link_to "Sign up", new_user_registration_path, class: "link-url" %> or 
    <%= link_to "log in", new_user_session_path, class: "link-url" %> to save links to your profile.
  <% else %>
    <%= link_to "My Profile", user_profile_path, class: "link-url" %>
    <% if current_user.admin? %>
      <%= link_to "Blips", new_blip_path, class: "link-url" %>
    <% end %>
    <%= button_to "Sign out", destroy_user_session_path, class: "sign-out-btn", method: :delete %>
  <% end %>
</div>

<div class="form-wrapper">
  <%= render 'form' %>
</div>

<div id="links">
  <% @links.each do |link| %>
    <div class="link-item">
      <div class="link-content">
        <p class=>URL: <%= link_to "#{link.url}", link.url %></p>
        <p class=>Short: <%= link_to "#{link.shortened_url}", link.shortened_url %></p>
        <p>Clicks: <%= link.click_count %></p>
      </div>
      <div class="link-action">
        <%= link_to "Edit", link_edit_path(link), class: "show-link-btn", id: "show-link-#{link.id}" %>
        <button class="copy-btn" data-clipboard-text="<%= "#{link.shortened_url}" %>">Copy</button>
        <% if current_user && (current_user.admin? || current_user.user?) %>
          <%= button_to "Delete", link_path(link), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-link-btn" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if current_user %>
  <%= link_to 'Export as CSV', export_to_csv_path, class: "copy-btn info" %>
<% end %>

<div class="pagination link-url">
  <%= paginate @links %>
</div>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/profile.html.erb
<div class="profile">
  <h1>My Links</h1>
  <%= link_to "Home", root_path, class: "link-url" %>
  <% @links.each do |link| %>
    <div class="link-item profile-page-item">
      <div class="link-content">
      <p class="link-short"><%= link_to "#{link.url}", link.url %></p>
      <p class="link-short"><%= link_to "#{root_url}" + "#{link.link_id}", "#{root_url}" + "#{link.link_id}" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>